# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.network "public_network", bridge: [
    "en0: Wi-Fi (Wireless)"
  ]

  config.vm.provider "virtualbox" do |cfg|
    cfg.linked_clone = true
    cfg.memory = "1024"
    cfg.cpus = 1
  end

  config.vm.define "alpine" do |alpine|
    alpine.vm.hostname    = "alpine"
    alpine.vm.box         = "generic/alpine38"
    alpine.vm.box_version = "v3.2.14"
    alpine.vm.box_check_update = false
  end

end

