# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  

  config.vm.network "public_network", bridge: [
    "en0: Wi-Fi (Wireless)"
  ]

  config.vm.provider "virtualbox" do |cfg|
    cfg.linked_clone = true
    cfg.memory = "2048"
    cfg.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname    = "ubuntu"
    ubuntu.vm.box         = "bento/ubuntu-20.04"
    ubuntu.vm.box_version = "202008.16.0"
    ubuntu.vm.box_check_update = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y lxc-utils
    snap install lxd
  SHELL
end
